### PR TITLE
Split into a library and a binary crate 

### PR DESCRIPTION
**Pull request by koute**

### CODE REVIEW

**Comment by koute** [comment]
...I'm not 100% sure if this is the correct way to have a binary and a library together; if you'd like to have it organized some other way I'd be happy to change it.

**Comment by alexcrichton** [comment]
Thanks! This division seems fine by me. Could the license/readme files be replaced with symlinks to avoid duplication? Additionally, perhaps the one public interface of the crate could just be the `Path`-based interface? (or maybe also including a slice/vec taking interface?) I was just thinking it's probably best for now to avoid exposing `parity-wasm` as a public dependency (so we can change it freely)

**Comment by koute** [comment]
Done!

I've replaced the licenses and the readme with symlinks, hidden parity_wasm (which also included adding a wrapper for parity_wasm's `Error` type) and replaced the function which took a `Module` with one that takes a slice.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
